# Generated by Django 5.1.7 on 2025-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_submittedform"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedform",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submittedform",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("returned", "Returned for Changes"),
                    ("approved", "Approved"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="submittedform",
            name="form_type",
            field=models.CharField(max_length=50),
        ),
    ]
