# Generated by Django 5.1.7 on 2025-03-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_submittedform_comments_submittedform_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
