# Generated by Django 5.1.7 on 2025-03-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_student_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmittedFormVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="submitted_forms/")),
                ("version_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="approver_signatures/"
                    ),
                ),
                (
                    "submitted_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="users.submittedform",
                    ),
                ),
            ],
            options={
                "unique_together": {("submitted_form", "version_number")},
            },
        ),
    ]
