# Generated by Django 5.1.7 on 2025-03-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_submittedformversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submittedform",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="submitted_forms/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="submittedformversion",
            name="approver_signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="approver_signatures/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="submittedformversion",
            name="pdf_file",
            field=models.FileField(upload_to="submitted_forms/%Y/%m/%d/"),
        ),
    ]
