# Generated by Django 5.1.7 on 2025-04-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_delegation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submittedform",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("returned", "Returned for Changes"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
