# Generated by Django 5.1.7 on 2025-04-20 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_submittedform_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.unit",
            ),
        ),
    ]
