# Generated by Django 5.1.7 on 2025-04-20 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_customuser_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedform",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
