# Generated by Django 5.1.7 on 2025-04-21 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_submittedform_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="parent_unit",
        ),
        migrations.AddField(
            model_name="unit",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subunits",
                to="users.unit",
            ),
        ),
    ]
